### ISSUE TITLE
View/Edit option in Data Management 

### ISSUE THREAD

**Issue by cegannon1** [EvilJinious1/trips#11]
Have successfully loaded 25-LY .chv dataset. Stars display. However, under the view/edit option in Dataset Management, no data appears on the table. How do I get that?

**Comment by EvilJinious1** [comment]
yes, fixing that now. I know what it is. If you run the Query dialog, it resets it.

**Comment by EvilJinious1** [comment]
problem will be fixed in 0.2 release
