### ISSUE TITLE
Plot not centered in plot window. 

### ISSUE THREAD

**Issue by BoatrightTBC** [EvilJinious1/trips#14]
The plot of stars is centered in a theoretical window with no sidebar. If you turn the sidebar off, the plot is centered correctly in the window. Since the sidebar is on by default, that means that the plot is lopsided.  

My suggestion is, turn the sidebar off by default. There's nothing that happens in the sidebar that the menu doesn't cover.  

I'll have seperate comments about the sidebar in a different issue.

**Comment by EvilJinious1** [comment]
ok, easy enough, Will put in 0.3 release

**Comment by EvilJinious1** [comment]
alright this is done, the side panel is off by default and can be toggle on
