### ISSUE TITLE
status bar font size and color poor 

### ISSUE THREAD

**Issue by BoatrightTBC** [EvilJinious1/trips#15]
Basically, I can barely read the statusbar entry that says "50LY" for example.  Font way small, and green? Really?

**Comment by EvilJinious1** [comment]
ok, I'll use perhaps blue and a larger font with a more explanatory message

**Comment by EvilJinious1** [comment]
will put in version 0.3

**Comment by EvilJinious1** [comment]
done. Will be in next version
