### ISSUE TITLE
Star labels on the grid....color

### ISSUE THREAD

**Issue by cegannon1** [EvilJinious1/trips#4]
the colorization of the stars while,helpful in one way ,actually significantly detracts from both readability and detectability of desired systems. The red does not read well and the Orange is not much better. And there are so much of these colors compared to the yellow or the white, that you have a largely unreadable array of object labels. I think we need to find a single color for stellar labeling and maybe make label:stellar colorization a toggle activated/deactivated option. For somebody who wants a snapshot of certain kinds of stars at a moments notice. (But I suspect there may be more elegant ways of doing that anyhow.)

**Comment by EvilJinious1** [comment]
I can add a floating preference dialog for star colors that allows you to show the colors and have them change in real time to see the result.
Would that work?

**Comment by cegannon1** [comment]
If we are talking about the labels of the stars, then yes that would work wonderfully. If we are talking about the stars themselves, I think it becomes more important that they keep their color..

Also, with the labels occupying so much compared of screen space, you don't even see the color of the stars themselves because most of the color on the screen is projected by the labels. When the labels all become a uniform color, then the color of the individual stars is going to pop more.

Sent from my Verizon, Samsung Galaxy smartphone

________________________________

**Comment by cegannon1** [comment]
I would add that  If it is not too cumbersome, there be a mechanism for choosing which colors are shown. But I am also mindful that that could be adding just one too many Bells and whistles that get too confusing for user.

Sent from my Verizon, Samsung Galaxy smartphone

________________________________

**Comment by cegannon1** [comment]
Star labels are still color-keyed to spectral type. Default should be one color (greyed-white). Coloring of names is not really needed. Maybe useful as a toggle feature.

**Comment by EvilJinious1** [comment]
yeah, I haven't fixed that yet. I fixed a null of other things that were causing crashes and limiting funnctionailty.
I'll fix that one in the next version

**Comment by EvilJinious1** [comment]
ok, I just added a color selection dialog. 
I also changed the defaults to make the colors less garish
this will be in release 0.2
